version: '3'

services:
  # Application service for config-rest-api
  cmc:
    image: lichbalab:cmc-2024.1
    ports:
      - "8080:8080"
      - "5005:5005" #Debug port
    restart: always
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ksc
      DB_USERNAME: postgres
      DB_PASSWORD: admin
    depends_on:
      - postgres

  # PostgreSQL service
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ksc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: